//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surveys
    {
        public int Id { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string CabinType { get; set; }
        public Nullable<int> Q1 { get; set; }
        public Nullable<int> Q2 { get; set; }
        public Nullable<int> Q3 { get; set; }
        public Nullable<int> Q4 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Ratings Ratings { get; set; }
        public virtual Ratings Ratings1 { get; set; }
        public virtual Ratings Ratings2 { get; set; }
        public virtual Ratings Ratings3 { get; set; }
    }
}
